"""initial

Revision ID: 55eed8370cca
Revises: 
Create Date: 2023-05-15 23:38:08.856571

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55eed8370cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # writing the code to create the tables
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("username", sa.String, unique=True, index=True),

        sa.Column("email", sa.String, unique=True, index=True),
        sa.Column("password", sa.String),
    )
    op.create_table(
        "addresses",
        sa.Column("address_id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("street", sa.String),
        sa.Column("city", sa.String),
        sa.Column("state", sa.String),
        sa.Column("country", sa.String),
    )
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String),
        sa.Column("description", sa.String),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String),
        sa.Column("description", sa.String),
        sa.Column("price", sa.Integer),
        sa.Column("quantity", sa.Integer),
        sa.Column("category_id", sa.Integer, sa.ForeignKey("categories.category_id")),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("address_id", sa.Integer, sa.ForeignKey("addresses.address_id")),
        sa.Column("total", sa.Float),
        sa.Column("status", sa.String),
    )
    op.create_table(
        "order_products",
        sa.Column("order_product_id", sa.Integer, primary_key=True),
        sa.Column("order_id", sa.Integer, sa.ForeignKey("orders.order_id")),
        sa.Column("product_id", sa.Integer, sa.ForeignKey("products.product_id")),
        sa.Column("quantity", sa.Integer),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_products")
    op.drop_table("orders")
    op.drop_table("products")
    op.drop_table("categories")
    op.drop_table("addresses")
    op.drop_table("users")
