"""change data type of created_add for order

Revision ID: 5b896b198f94
Revises: bfdea1a4adbe
Create Date: 2023-05-16 04:49:18.797647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b896b198f94'
down_revision = 'bfdea1a4adbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at', type_=sa.String)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at', type_=sa.DateTime)
    # ### end Alembic commands ###
