"""add column total_amount

Revision ID: 6f42121eccea
Revises: f7cdd7de9afd
Create Date: 2023-05-16 04:29:06.972358

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6f42121eccea'
down_revision = 'f7cdd7de9afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.Float))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
